global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"

scrape_configs:
  - job_name: "tensorflow-serving"
    scrape_interval: 15s 
    metrics_path: /monitoring/prometheus/metrics
    scheme: https  # Tambahkan ini untuk HTTPS
    static_configs:
      - targets: ['mlops-production-fd3b.up.railway.app:443']  # Tambahkan port 443 untuk HTTPS
    
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']